# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-19 15:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('job_Description', models.TextField()),
                ('min_Qualifications', models.CharField(choices=[('CB', 'Computer Science Bachelor Degree'), ('LL', 'Law Licence Degree'), ('AB', 'Accounting Bachelor Degree')], default='CB', max_length=2)),
                ('gender_Required', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('starting_Salary', models.PositiveIntegerField()),
                ('daily_Working_Hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(12)])),
                ('weekly_Working_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=25)),
                ('middle_Name', models.CharField(blank=True, max_length=25)),
                ('last_Name', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_Birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('academic_Degree', models.CharField(choices=[('CB', 'Computer Science Bachelor Degree'), ('LL', 'Law Licence Degree'), ('AB', 'Accounting Bachelor Degree')], default='CB', max_length=2)),
                ('date_of_Graduation', models.DateField()),
            ],
        ),
    ]
