# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-20 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_auto_20160719_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['first_Name', 'last_Name']},
        ),
    ]
