# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-26 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_auto_20160720_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['title'], 'verbose_name_plural': 'jobs'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['first_Name', 'last_Name'], 'verbose_name_plural': 'profiles'},
        ),
    ]
