# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-30 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0006_auto_20160730_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_jobs',
            field=models.ManyToManyField(blank=True, related_name='saved_jobs', to='career.Job', verbose_name='Saved jobs'),
        ),
    ]
