# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-30 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0008_auto_20160730_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='jobs_applied',
            field=models.ManyToManyField(blank=True, related_name='applied_job', to='career.Job', verbose_name='Jobs he applied on'),
        ),
    ]
