# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-31 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0009_auto_20160730_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_profiles',
            field=models.ManyToManyField(blank=True, related_name='_profile_saved_profiles_+', to='career.Profile', verbose_name='Saved profiles'),
        ),
    ]
